export enum ChartTypeEnum {
    VERTICAL_BAR = "VERTICAL_BAR",
    PIVOT_TABLE = "PIVOT_TABLE",
    HORIZONTAL_BAR = "HORIZONTAL_BAR",
    LINE = "LINE",
    STATUS_METER = "STATUS_METER",
    PIE = "PIE",
    BUBBLE = "BUBBLE",
    STACKED_VERTICAL_BAR = "STACKED_VERTICAL_BAR",
    TREE_MAP = "TREE_MAP",
    AREA = "AREA",
}