export enum DashboardContentTypeEnum {
    INSIGHT = "INSIGHT",
    TOTAL_SPEND = "TOTAL_SPEND",
    COST_DETAIL = "COST_DETAIL",
    COST_PROJECTION = "COST_PROJECTION",
    BUDGET = "BUDGET",
    
    TOP_X_PROJECT = "TOP_X_PROJECT",
    OVERVIEW_PROJECT = "OVERVIEW_PROJECT",
    OVERVIEW_CLOUD = "OVERVIEW_CLOUD",
    OVERVIEW_MULTI_CLOUD = "OVERVIEW_MULTI_CLOUD",
}